site_name: DKMS Training Portal

theme:
  name: material

nav:
  - Home: index.md
  - Docker: docker.md
  - Linux: linux.md
  - Exasol:
      - Introdução: exasol.md
      - BucketFS: bucketfs.md
      - DBeaver: dbeaver.md
  - GitHub: github.md